### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by yashpalgoyal1304** [D3SOX/awesome-software#15]
HI! found you via https://github.com/florisboard/florisboard/issues/320#issuecomment-774082999 Your profile pic is suuper nice:  [24937357](https://user-images.githubusercontent.com/19423063/108614742-4679d900-7423-11eb-8268-9ff30cc6f5d2.png)

Just was having a look at your profile's pinned repo section, and found this: https://awesome-software.d3sox.me . It seems awesome - and i just found/recalled that there is even a version of [chromium: degooglified 🡭](https://github.com/D3SOX/awesome-software/tree/master/docs/desktop#ungoogled-chromium) - lol, I thought chromium is enough.

I am thinking of making some suggestions (some long time later though) so, just asking before hand:
1. Did you thought about using tables? or smth else similar, so that space can be saved?\
If yes, then why did u not apply that?\
If no, then would that be welcome?\
For example, here {well, all of them, but still} : https://awesome-software.d3sox.me/android/ 
![image](https://user-images.githubusercontent.com/19423063/108614615-0e25cb00-7422-11eb-80ab-60e27246f419.png)
2. Is there some criteria i should keep in mind while suggesting apps? The apps i am thinking of suggesting are all gratis - not necessarily free(dom) though. Some are discontinued officially, but work perfectly fine otherwise.\
I have read it: https://awesome-software.d3sox.me/introduction/ , and though it says nothing rigid, i still thought to confirm.
3. Novel: Any plans to add linux phones in platform list? 😋 \
Like Librem 5, and Pinephone - i know that they are suuper new, and it would be against the introduction ("the apps i use"), and the apps may already be given under linux category already. But still, this would contain apps that are optimised for mobile interface.\
While i dont know such apps personally either, but maybe u can put a demand/request for community input?

**Comment by D3SOX** [comment]
Hey, thanks for you detailed comment.

About the spacing: It was just a format I used when I put it together originally. It can definitely improved. Do you want to try improving it? PRs are welcome ;)

For the criteria: If you find some discontinued apps I can add a discontinued tag to them and maybe there is a fork or an alternative. I want to provide several apps for each category so the reader can look through them and decide which they like the most. Maybe an app A that I use is the best for me but an app B has a feature that they always wanted so they like B better.
Don't hesitate to suggest some, we can discuss about adding them.

Linux phones: They are not all apps I use. As I said it's about recommending alternatives (mostly to big brother apps) and I'm not using all of them. (On android f.e. I just use Bromite). So yeah adding a separate Linux phone section would be welcome.

**Comment by yashpalgoyal1304** [comment]
so, long time from my side 😅 

=== Android ===
* Markor : [net.gsantner.markor] (for [#note-taking])  
* GApps Browser: [com.tobykurien.google_news]

[#note-taking]: https://awesome-software.d3sox.me/android/#note-taking
[net.gsantner.markor]: https://f-droid.org/packages/net.gsantner.markor
[com.tobykurien.google_news]: https://f-droid.org/packages/com.tobykurien.google_news

=== Windows only ===
* ShareX   
screenshot capture & annotations. gif/video recording, image effects and piping, hugely multipurpose   
https://getsharex.com/   
https://github.com/ShareX/ShareX/

* SumatraPDF  
Extremely lightweight pdf reader (also has pdf vector based annotations)
https://www.sumatrapdfreader.org/  
https://github.com/sumatrapdfreader  

=== lin, mac, win (c-p desk) ===
* File browsers  
all above are based on personal experience, but foll are just based on wikipedia  
dual pane file explorers
   * mucommander  
   https://www.mucommander.com/  
   https://github.com/mucommander/mucommander  
   * doublecommander  
   https://doublecommander.com/
   https://github.com/doublecmd/doublecmd

**Comment by yashpalgoyal1304** [comment]
i am thinking of opening an mr,

do u have written the categories of softwares in some particular oders? 'cz i think that order of the categories of the software can be modified/improved a bit

**Comment by D3SOX** [comment]
Hi, I haven't worked on the project for quite some time. I've just put what I use or recommend the most first and then the rest. Feel free to open a PR, we can still discuss the changes then.
