### ISSUE TITLE
a new pdf reader software is awaited for android

### ISSUE THREAD

**Issue by yashpalgoyal1304** [D3SOX/awesome-software#66]
there is a new updated fork to the pdf viewer plus - it's out there on izzy droid's fdroid repository, it's under work to be published on official f-droid repo.

so, i am opening this issue just as a reminder for myself to ping back when that gets successfully published on official f-droid repo

link to the repo of the reader: https://gitlab.com/mudlej_android/mj_pdf_reader

https://github.com/D3SOX/awesome-software/blob/332cc7d20aefc2e0b6c5d0088d3b36c5c7ba5cb8/docs/android/index.md?plain=1#L431-L435

**Comment by D3SOX** [comment]
Thanks for the info! My current favorite is actually PDF Viewer Plus and while it's still great I'm looking forward to some UI improvements and features like a search
